port to Gtk3
jvolkening/gloc pull request #5
Opened 2021-03-22 02:19 UTC by uhoreg

I'm not a Gtk expert, but from my quick testing, this seems to work.

I've also changed the ordering of the file picker dialogs to be consistent with each other (using the order preferred by the GNOME HIG)

2021-03-22 07:41 UTC, jvolkening requested changes
Thanks for the PR. Looks good except for the two places indicated.

2021-03-22 07:41 UTC, jvolkening commented on gloc
> +my $it = Gtk3::IconTheme::get_default();
Since `add_builtin_icon` is now a function, this line is no longer needed.

2021-03-22 07:41 UTC, jvolkening commented on gloc
>              $loader->write( decode_base64( $encoded{$_} ) );
From testing, it appears that a change is needed here to the format of the argument to `write()`. I suggest:
```
my $img_data = decode_base64($encoded{$_});
$loader->write( [unpack 'C*', $img_data] );
```

2021-03-22 14:40 UTC, uhoreg commented
Thanks for the quick review.  I've made the changes as requested.

2021-03-26 04:50 UTC, jvolkening approved these changes

2021-03-26 04:51 UTC, merged

2021-03-26 04:52 UTC, jvolkening commented
Thank you @uhoreg. I will add you as a contributor before merging this to master.